# Generated by Django 5.2.7 on 2025-10-22 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance', models.CharField(choices=[('ZENKUTSU_DACHI', 'Zenkutsu Dachi'), ('KOKUTSU_DACHI', 'Kokutsu Dachi'), ('KIBA_DACHI', 'Kiba Dachi')], max_length=30)),
                ('quantity', models.PositiveIntegerField(default=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='techniques', to='idogueiko.category')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('OI', 'Oi'), ('GYAKU', 'Gyaku')], default='OI', max_length=30)),
                ('order', models.PositiveIntegerField(default=1)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idogueiko.sequence')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='idogueiko.technique')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('sequence', 'order')},
            },
        ),
        migrations.AddField(
            model_name='sequence',
            name='techniques',
            field=models.ManyToManyField(related_name='sequences', through='idogueiko.SequenceTechnique', to='idogueiko.technique'),
        ),
    ]
