# Generated by Django 5.2.7 on 2025-10-23 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idogueiko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencetechnique',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idogueiko.technique'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='idogueiko.category'),
        ),
    ]
